version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calmato-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs 